name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies and build
        run: |
          cd packages/auth
          npm install
          npm run build
          pwd
      
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_PRIVATE_KEY}}
          workload_identity_provider: ${{secrets.GCP_PRIVATE_KEY}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'packages/auth/dist'
          destination: 'mfe-deploy/auth/latest'
