name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run : pwd

      - name: GCP Auth 
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.GCP_PRIVATE_KEY}}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
      - name: Deploy
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'packages/auth/dist'
          destination: 'mfe-deploy/auth/latest'
          
