name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'packages/auth/**'

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: google-github-actions/setup-gcloud@v2
        env:
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          GCP_PRIVATE_ID: ${{ secrets.GCP_PRIVATE_ID }}
          GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
      - name: Deploy
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '../../packages/auth/dist'
          destination: 'mfe-deploy/auth/latest'
          
